branches:
  only:
    - master

environment:
  NETLIFY_TOKEN:
    secure: 0c96e45b397d407cf5096d4c074dbb9ad4b818b86bb8601da353fcea8deccacf

# Temporarily needed until curl added to PATH
# See http://help.appveyor.com/discussions/problems/6312-curl-command-not-found
# And https://github.com/appveyor/ci/issues/1431
install:
- set PATH=C:\Program Files\Git\mingw64\bin;%PATH%

build_script:
  - ps: .\build.ps1 -Target "AppVeyor"
